<?php

class ReportService {
    /**
     * Generates a valid standard PDF 1.4 document from inspection data.
     */
    public static function generateInspectionPdf(array $inspection, string $outputPath): string {
        $title = "MoSJE FIELD INSPECTION REPORT #" . $inspection['id'];
        $tender = $inspection['tender_number'] . " - " . $inspection['tender_title'];
        $status = $inspection['status'];
        $inspector = $inspection['inspector_name'] ?? 'N/A';
        $verifiedBy = $inspection['verified_by_name'] ?? 'Pending';
        $progress = number_format((float)($inspection['overall_progress'] ?? 0), 1) . "%";
        $spent = "INR " . number_format((float)($inspection['actual_spent_recorded'] ?? 0), 2);
        $remarks = substr(str_replace(["\r", "\n", "(", ")"], ' ', $inspection['remarks'] ?? 'No remarks provided'), 0, 100);

        // Build text content commands
        $stream = "BT\n";
        $stream .= "/F1 18 Tf\n";
        $stream .= "50 780 Td\n";
        $stream .= "(MINISTRY OF SOCIAL JUSTICE & EMPOWERMENT) Tj\n";

        $stream .= "/F2 12 Tf\n";
        $stream .= "0 -22 Td\n";
        $stream .= "(Field Monitoring & Quality Inspection Sign-off Report) Tj\n";

        $stream .= "/F1 14 Tf\n";
        $stream .= "0 -30 Td\n";
        $stream .= "(" . self::escapePdf($title) . ") Tj\n";

        $stream .= "/F2 10 Tf\n";
        $stream .= "0 -25 Td\n";
        $stream .= "(Tender: " . self::escapePdf($tender) . ") Tj\n";
        $stream .= "0 -16 Td\n";
        $stream .= "(Lifecycle Status: " . self::escapePdf($status) . " | Severity: " . self::escapePdf($inspection['severity'] ?? 'NONE') . ") Tj\n";
        $stream .= "0 -16 Td\n";
        $stream .= "(Field Inspector: " . self::escapePdf($inspector) . ") Tj\n";
        $stream .= "0 -16 Td\n";
        $stream .= "(Verifying Officer: " . self::escapePdf($verifiedBy) . ") Tj\n";
        $stream .= "0 -16 Td\n";
        $stream .= "(Recorded Progress: " . self::escapePdf($progress) . " | Spent to Date: " . self::escapePdf($spent) . ") Tj\n";
        $stream .= "0 -16 Td\n";
        $stream .= "(Basis of Expenditure: " . self::escapePdf($inspection['spent_basis'] ?? 'MB Book') . ") Tj\n";
        $stream .= "0 -20 Td\n";
        $stream .= "(Field Remarks: " . self::escapePdf($remarks) . ") Tj\n";

        // Section: Evidence Telemetry
        $stream .= "0 -30 Td\n";
        $stream .= "/F1 12 Tf\n";
        $stream .= "(DIGITAL EVIDENCE & GEO-LOCATION TELEMETRY) Tj\n";
        $stream .= "/F2 9 Tf\n";

        $items = $inspection['evidence_items'] ?? [];
        if (empty($items)) {
            $stream .= "0 -18 Td\n";
            $stream .= "(No media items attached to this inspection record.) Tj\n";
        } else {
            foreach ($items as $idx => $item) {
                $itemLine = sprintf(
                    "#%d [%s] Lat: %.5f, Lng: %.5f (Accuracy: %.1fm) | Capture Time: %s",
                    $idx + 1,
                    $item['file_type'],
                    (float)$item['latitude'],
                    (float)$item['longitude'],
                    (float)$item['accuracy'],
                    $item['device_capture_time']
                );
                $stream .= "0 -15 Td\n";
                $stream .= "(" . self::escapePdf($itemLine) . ") Tj\n";
            }
        }

        // Section: Quality Checks
        $stream .= "0 -25 Td\n";
        $stream .= "/F1 12 Tf\n";
        $stream .= "(QUALITY CHECKLIST OUTCOME) Tj\n";
        $stream .= "/F2 9 Tf\n";

        $qcs = $inspection['quality_checks'] ?? [];
        if (empty($qcs)) {
            $stream .= "0 -18 Td\n";
            $stream .= "(Quality checklist completed without itemized exceptions.) Tj\n";
        } else {
            foreach ($qcs as $qc) {
                $qcLine = sprintf(
                    "- %s: [%s] %s",
                    $qc['item_name'],
                    $qc['status'],
                    $qc['is_critical'] ? '(CRITICAL)' : ''
                );
                $stream .= "0 -14 Td\n";
                $stream .= "(" . self::escapePdf($qcLine) . ") Tj\n";
            }
        }

        // Footer
        $stream .= "0 -40 Td\n";
        $stream .= "/F2 8 Tf\n";
        $stream .= "(Generated by Smart Real-Time Inspection Portal - SIH26095 MoSJE | Watermark Verified) Tj\n";
        $stream .= "ET\n";

        // Assembly of PDF-1.4 binary structure
        $objects = [];
        $objects[1] = "<< /Type /Catalog /Pages 2 0 R >>";
        $objects[2] = "<< /Type /Pages /Kids [3 0 R] /Count 1 >>";
        $objects[3] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>";
        $objects[4] = "<< /Length " . strlen($stream) . " >>\nstream\n" . $stream . "endstream";
        $objects[5] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";
        $objects[6] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";

        $pdf = "%PDF-1.4\n";
        $xref = ["0000000000 65535 f \n"];

        foreach ($objects as $id => $obj) {
            $xref[$id] = sprintf("%010d 00000 n \n", strlen($pdf));
            $pdf .= "{$id} 0 obj\n{$obj}\nendobj\n";
        }

        $xrefOffset = strlen($pdf);
        $pdf .= "xref\n0 " . (count($objects) + 1) . "\n";
        foreach ($xref as $entry) {
            $pdf .= $entry;
        }

        $pdf .= "trailer\n<< /Size " . (count($objects) + 1) . " /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF";

        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0777, true);
        }

        file_put_contents($outputPath, $pdf);
        return $outputPath;
    }

    private static function escapePdf(string $text): string {
        $clean = preg_replace('/[^\x20-\x7E]/', ' ', $text);
        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $clean);
    }

    /**
     * Generates a CSV file from tenders list.
     */
    public static function generateTendersCsv(array $tenders, string $outputPath): string {
        $handle = fopen($outputPath, 'w');
        fputcsv($handle, [
            'ID',
            'Tender Number',
            'Title',
            'Category',
            'District',
            'State',
            'Contractor Name',
            'Sanctioned Amount (INR)',
            'Actual Spent (INR)',
            'Progress %',
            'Spent %',
            'Variance %',
            'Status',
            'Variance Flag',
            'Delay Flag',
            'Scheduled End Date',
        ]);

        foreach ($tenders as $t) {
            fputcsv($handle, [
                $t['id'],
                $t['tender_number'],
                $t['title'],
                $t['category_name'] ?? $t['category'] ?? '',
                $t['district_name'] ?? '',
                $t['state_name'] ?? '',
                $t['contractor_name'] ?? '',
                $t['sanctioned_amount'],
                $t['actual_spent'],
                $t['progress_percentage'],
                $t['spent_percentage'],
                $t['variance'],
                $t['status'],
                !empty($t['variance_flag']) ? 'YES' : 'NO',
                !empty($t['delay_flag']) ? 'YES' : 'NO',
                $t['scheduled_end_date'] ?? '',
            ]);
        }
        fclose($handle);
        return $outputPath;
    }
}
