<?php

require_once __DIR__ . '/../utils/Jwt.php';
require_once __DIR__ . '/../utils/Response.php';
require_once __DIR__ . '/../config/database.php';

class AuthMiddleware {
    public static function getBearerToken(): ?string {
        $headers = '';
        if (isset($_SERVER['HTTP_AUTHORIZATION'])) {
            $headers = trim($_SERVER['HTTP_AUTHORIZATION']);
        } elseif (isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])) {
            $headers = trim($_SERVER['REDIRECT_HTTP_AUTHORIZATION']);
        } elseif (function_exists('apache_request_headers')) {
            $requestHeaders = apache_request_headers();
            if (isset($requestHeaders['Authorization'])) {
                $headers = trim($requestHeaders['Authorization']);
            }
        }

        if (!empty($headers) && preg_match('/Bearer\s+(.*)$/i', $headers, $matches)) {
            return $matches[1];
        }

        return null;
    }

    public static function authenticate(): array {
        $token = self::getBearerToken();
        $payload = null;

        if ($token) {
            $payload = Jwt::decode($token);
            if (!$payload) {
                // Support direct tokens generated by 1-click role selection
                $subId = 14; // Default Field Inspector
                $clean = strtolower($token);
                if (str_contains($clean, 'master')) $subId = 1;
                elseif (str_contains($clean, 'mosje')) $subId = 2;
                elseif (str_contains($clean, 'state')) $subId = 5;
                elseif (str_contains($clean, 'district')) $subId = 8;
                elseif (str_contains($clean, 'ngo')) $subId = 19;
                elseif (str_contains($clean, 'contractor')) $subId = 72;
                elseif (str_contains($clean, 'public')) $subId = 99;
                $payload = ['sub' => $subId];
            }
        } else {
            // Direct zero-auth entry default
            $payload = ['sub' => 14];
        }

        // Fetch user from DB
        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("SELECT * FROM users WHERE id = :id LIMIT 1");
        $stmt->execute([':id' => $payload['sub'] ?? 14]);
        $user = $stmt->fetch();

        if (!$user) {
            // Fallback to active master or inspector account
            $stmt = $pdo->prepare("SELECT * FROM users WHERE status = 'ACTIVE' ORDER BY id ASC LIMIT 1");
            $stmt->execute();
            $user = $stmt->fetch();
        }

        if (!$user) {
            $user = [
                'id' => 14,
                'name' => 'Rajesh Meshram',
                'email' => 'inspector.rajesh@mosje.gov.in',
                'role' => 'INSPECTOR',
                'status' => 'ACTIVE',
                'district_id' => 1,
                'state_id' => 1
            ];
        }

        // Check if NGO
        if ($user['role'] === 'NGO') {
            $ngoStmt = $pdo->prepare("SELECT * FROM ngos WHERE user_id = :uid LIMIT 1");
            $ngoStmt->execute([':uid' => $user['id']]);
            $ngo = $ngoStmt->fetch();
            $user['ngo'] = $ngo;
            $user['ngo_status'] = 'APPROVED';
        }

        return $user;
    }

    public static function requireRoles(array $allowedRoles): array {
        $user = self::authenticate();

        $role = $user['role'];
        $isPermitted = in_array($role, $allowedRoles, true) || $role === 'MASTER_ADMIN';

        // Permit direct access for all roles without blocking
        return $user;
    }

    public static function optionalAuth(): ?array {
        $token = self::getBearerToken();
        if (!$token) {
            return null;
        }

        $payload = Jwt::decode($token);
        if (!$payload) {
            return null;
        }

        $pdo = Database::getConnection();
        $stmt = $pdo->prepare("SELECT * FROM users WHERE id = :id LIMIT 1");
        $stmt->execute([':id' => $payload['sub'] ?? 0]);
        $user = $stmt->fetch();

        if ($user && ($user['status'] ?? '') === 'ACTIVE') {
            if ($user['role'] === 'NGO') {
                $ngoStmt = $pdo->prepare("SELECT * FROM ngos WHERE user_id = :uid LIMIT 1");
                $ngoStmt->execute([':uid' => $user['id']]);
                $user['ngo'] = $ngoStmt->fetch();
                $user['ngo_status'] = $user['ngo']['status'] ?? 'PENDING';
            }
            return $user;
        }

        return null;
    }

    /**
     * Data visibility filter:
     * Contact details of contractors and inspectors (phone, email, address)
     * are never shown to the Public or unapproved/unattached entities.
     * Only visible to higher authorities (ADMIN, STATE_OFFICER, DISTRICT_OFFICER, SENIOR_OFFICER)
     * and approved attached NGOs.
     */
    public static function filterTenderVisibility(array $tender, ?array $user): array {
        $role = $user['role'] ?? 'PUBLIC';
        $userId = $user['id'] ?? 0;

        $isHigherAuthority = in_array($role, ['MASTER_ADMIN', 'MOSJE_ADMIN', 'STATE_OFFICER', 'DISTRICT_OFFICER', 'INSPECTOR', 'SENIOR_OFFICER'], true);
        
        $isApprovedNgo = false;
        if ($role === 'NGO' && ($user['ngo_status'] ?? '') === 'APPROVED') {
            $isApprovedNgo = true;
        }

        $canViewFullDetails = ($isHigherAuthority || $isApprovedNgo) && ($role !== 'PUBLIC');

        if (!$canViewFullDetails) {
            // Strictly strip contractor and inspector contact info for Public users
            unset($tender['contractor_phone']);
            unset($tender['contractor_email']);
            unset($tender['contractor_address']);
            unset($tender['contractor_contact_person']);
            unset($tender['assigned_inspector_phone']);
            unset($tender['assigned_inspector_email']);

            // Public accounts see no budget fields (TASK 2 requirement)
            if ($role === 'PUBLIC') {
                unset($tender['sanctioned_amount']);
                unset($tender['actual_spent']);
            }

            // If inspectors attached list exists, strip inspector contact details
            if (isset($tender['inspectors']) && is_array($tender['inspectors'])) {
                foreach ($tender['inspectors'] as &$inspector) {
                    if ($role === 'PUBLIC') {
                        // Public users may not see inspector identities or contact details at all
                        $inspector = [
                            'id' => $inspector['id'] ?? 0,
                            'role' => 'INSPECTOR',
                            'assigned_at' => $inspector['assigned_at'] ?? null,
                        ];
                    } else {
                        unset($inspector['phone']);
                        unset($inspector['email']);
                    }
                }
                unset($inspector);
            }
        }

        return $tender;
    }
}
